apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
  namespace: dev
  labels:
    app: assets-pod 
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: assets-pod 
  template:
    metadata:
      labels:
        app: assets-pod
    spec:
      securityContext:
        {}
      containers:
        - name: assets
          envFrom:
            - configMapRef:
                name: assets-config
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          image: "public.ecr.aws/aws-containers/retail-store-sample-assets:0.8.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 128m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: assets-svc
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8083
      protocol: TCP
      targetPort: http
      nodePort: 30013
  selector:
    app: assets-pod

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: assets-config
  namespace: dev
data:
  PORT: "8083"