apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: dev
  labels:
    app: carts-pod  
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: carts-pod  
  template:
    metadata:
      labels:
        app: carts-pod
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: carts
          env:
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
          envFrom:
            - configMapRef:
                name: carts-config
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false #true
            runAsNonRoot: true
            runAsUser: 1000
          image: "public.ecr.aws/aws-containers/retail-store-sample-cart:0.8.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 128m
              memory: 256Mi
          

---

apiVersion: v1
kind: Service
metadata:
  name: carts-svc
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: http
      nodePort: 30012
  selector:
    app: carts-pod
  

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: carts-config
  namespace: dev
data:
  PORT: "80"
  SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
  SPRING_PROFILES_ACTIVE:  "dynamodb"
  CARTS_DYNAMODB_TABLENAME: "Items"
  #CARTS_DYNAMODB_CREATETABLE: "false"
  CARTS_DYNAMODB_CREATETABLE: "true"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  CARTS_DYNAMODB_ENDPOINT: "http://carts-dynamodb-svc:8000"
  