apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-checkout
  namespace: dev
  labels:
    app: redis-checkout-pod 
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: redis-checkout-pod 
  template:
    metadata:
      labels:
        app: redis-checkout-pod
    spec:
      securityContext:
        {}
      containers:
        - name: redis-checkout
          envFrom:
            - configMapRef:
                name: redis-checkout-config
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
          image: "public.ecr.aws/aws-containers/retail-store-sample-checkout:0.8.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          

---
apiVersion: v1
kind: Service
metadata:
  name: checkout-svc
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      targetPort: redis
  selector:
    app: redis-checkout-pod

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
  namespace: dev
data:
  #PORT: "8083"
  REDIS_URL: "redis://checkout-redis-svc:6379"
  ENDPOINTS_ORDERS: "http://orders-svc:80"