apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-dynamodb
  labels:
    app: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
        - name: dynamodb
          image: "amazon/dynamodb-local:1.20.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: dynamodb
              containerPort: 8000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: carts-dynamodb
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: dynamodb
  selector:
    app: dynamodb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamodb-config
  namespace: dev
data:
  PORT: 8000
  SPRING_PROFILES_ACTIVE:  "dynamodb"
  CARTS_DYNAMODB_TABLENAME: "Items"
  #CARTS_DYNAMODB_CREATETABLE: "false"
  CARTS_DYNAMODB_CREATETABLE: "true"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  