apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-postgres
  namespace: dev
  labels:
    app: orders-postgres-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgres-pod
  template:
    metadata:
      labels:
        app: orders-postgres-pod
    spec:
      containers:
        - name: postgresql
          image: "public.ecr.aws/docker/library/postgres:16.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orders-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-db-secret
                  key: password
            - name: PGDATA
              value: /data/pgdata
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: orders-postgresql-svc
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgressql
      protocol: TCP
      name: "postgressql"
  selector:
    app: orders-postgres-pod

---

apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
data:
  username: "b3JkZXJz"
  password: "QTRZNWY4Q1djU1hZaWloYw=="