apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-pod
  name: frontend-app
  namespace: dev
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
        - name: ui
          env:
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
          envFrom:
            - configMapRef:
                name: frontend-config
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "public.ecr.aws/aws-containers/retail-store-sample-ui:0.8.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 128m
              memory: 512Mi
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      nodePort: 30010
  selector:
    app: frontend-pod
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: dev
data:
  APPUSER : "appuser"
  APPUID : "1000"
  APPGID : "1000"
  ENDPOINTS_CATALOG: "http://catalog-svc:8081"
  ENDPOINTS_CARTS: "http://carts-svc:8082"
  ENDPOINTS_CHECKOUT: http://checkout
  ENDPOINTS_ORDERS: http://orders
  ENDPOINTS_ASSETS: http://assets
  