name: Create k3s Infra on AWS

on:
  workflow_dispatch:  # Her job manuel olarak çalıştırılabilir

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: K3s Cluster with Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        working-directory: k3s-terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: k3s-terraform
        run: terraform plan

      - name: Apply Terraform (Create K3s Cluster)
        working-directory: k3s-terraform
        run: terraform apply -auto-approve

  