name: Deploy App on AWS

on:
  workflow_dispatch:  # Her job manuel olarak çalıştırılabilir

permissions:
  id-token: write
  contents: read

jobs:

  deploy-ui:
    name: Deploy UI to K3s
    runs-on: self-hosted
    #needs: terraform-apply  # Runs after Terraform Apply
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set KUBECONFIG Environment Variable
        run: echo "KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV

      - name: Verify Kubernetes Connection
        run: sudo kubectl get nodes

      #- name: Apply Kubernetes Manifests
      #  run: sudo kubectl create ns dev

      - name: Apply Kubernetes Manifests
        run: sudo kubectl apply -f kubernetes-manifests/

      - name: Apply Kubernetes Ingress
        run: sudo kubectl apply -f kubernetes-ingress-files/

 
