name: Deploy App on AWS

on:
  workflow_dispatch:  # Her job manuel olarak çalıştırılabilir

permissions:
  id-token: write
  contents: read

jobs:

  deploy-ui:
    name: Deploy UI to K3s
    runs-on: self-hosted
    #needs: terraform-apply  # Runs after Terraform Apply
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Verify Kubernetes Connection
        run: kubectl get nodes

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f kubernetes-manifests/

 
